#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class Grid;
                ref class Button;
                ref class RelativePanel;
                ref class TextBlock;
                ref class TextBox;
                ref class AppBar;
            }
        }
    }
}

namespace UWP_DX11_XAML_
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ UIPanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ UImainContent;
        private: ::Windows::UI::Xaml::Controls::Grid^ userInputGrid;
        private: ::Windows::UI::Xaml::Controls::Button^ submitButton;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ fuc1Panel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ fuc2Panel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ lbPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ rbPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ numPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ numTxt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ numVal;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ rbTxt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ rbVal;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lbTxt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ lbVal;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fuc2Txt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ fuc2Val;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fuc1Txt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ fuc1Val;
        private: ::Windows::UI::Xaml::Controls::AppBar^ bottomAppBar;
    };
}

